# Generated by Django 2.0.1 on 2018-04-28 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(default='', max_length=100, verbose_name='学校')),
                ('school_url', models.URLField(default='', max_length=100, verbose_name='学校链接')),
                ('major', models.CharField(default='', max_length=100, verbose_name='主修专业')),
                ('edu_grade', models.CharField(default='', max_length=50, verbose_name='学历')),
                ('start_time', models.DateField(verbose_name='开始时间')),
                ('end_time', models.DateField(blank=True, verbose_name='结束时间')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=200, verbose_name='职能')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='项目名称')),
                ('url', models.URLField(default='https://github.com/githubError/', verbose_name='项目链接')),
                ('content', models.TextField(default='', verbose_name='描述')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(default='', max_length=100, verbose_name='单位名称')),
                ('company_url', models.URLField(default='', verbose_name='单位链接')),
                ('position', models.CharField(default='', max_length=100, verbose_name='职能')),
                ('start_time', models.DateField(verbose_name='入职时间')),
                ('end_time', models.DateField(blank=True, verbose_name='离职时间')),
                ('summary', models.TextField(default='', verbose_name='概述')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=200, verbose_name='内容')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10, verbose_name='姓名')),
                ('birthday', models.DateField(verbose_name='生日')),
                ('telephone', models.CharField(default='', max_length=20, verbose_name='电话')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='邮箱')),
                ('blog', models.URLField(default='', verbose_name='博客')),
                ('github', models.URLField(default='', verbose_name='GitHub')),
                ('introduce', models.TextField(default='', verbose_name='自我介绍')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='skill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resumes.UserInfo'),
        ),
        migrations.AddField(
            model_name='record',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resumes.UserInfo'),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resumes.UserInfo'),
        ),
        migrations.AddField(
            model_name='function',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resumes.Record'),
        ),
        migrations.AddField(
            model_name='education',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resumes.UserInfo'),
        ),
    ]
