# Generated by Django 2.0.2 on 2018-02-02 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resumes', '0002_userinfo_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(default='', max_length=10),
        ),
    ]
