# Generated by Django 2.0.2 on 2018-02-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resumes', '0003_auto_20180202_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='blog',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='github',
            field=models.URLField(default=''),
        ),
    ]
