# Generated by Django 2.0.2 on 2018-02-02 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resumes', '0004_auto_20180202_0554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(default='', max_length=100)),
                ('school_url', models.URLField(default='', max_length=100)),
                ('major', models.CharField(default='', max_length=100)),
                ('edu_grade', models.CharField(default='', max_length=50)),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
            ],
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(default='', max_length=100)),
                ('company_url', models.URLField(default='')),
                ('position', models.CharField(default='', max_length=100)),
                ('start_time', models.DateTimeField(verbose_name='入职时间')),
                ('end_time', models.DateTimeField(verbose_name='离职时间')),
                ('summary', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='introduce',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='skill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resumes.UserInfo'),
        ),
        migrations.AddField(
            model_name='record',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resumes.UserInfo'),
        ),
        migrations.AddField(
            model_name='function',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resumes.Record'),
        ),
        migrations.AddField(
            model_name='education',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resumes.UserInfo'),
        ),
    ]
