# Generated by Django 2.0.2 on 2018-02-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resumes', '0005_auto_20180202_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='edu_grade',
            field=models.CharField(default='', max_length=50, verbose_name='学历'),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_time',
            field=models.DateField(verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='education',
            name='major',
            field=models.CharField(default='', max_length=100, verbose_name='主修专业'),
        ),
        migrations.AlterField(
            model_name='education',
            name='school',
            field=models.CharField(default='', max_length=100, verbose_name='学校'),
        ),
        migrations.AlterField(
            model_name='education',
            name='school_url',
            field=models.URLField(default='', max_length=100, verbose_name='学校链接'),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_time',
            field=models.DateField(verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='function',
            name='content',
            field=models.CharField(default='', max_length=200, verbose_name='职能'),
        ),
        migrations.AlterField(
            model_name='record',
            name='company',
            field=models.CharField(default='', max_length=100, verbose_name='单位名称'),
        ),
        migrations.AlterField(
            model_name='record',
            name='company_url',
            field=models.URLField(default='', verbose_name='单位链接'),
        ),
        migrations.AlterField(
            model_name='record',
            name='end_time',
            field=models.DateField(verbose_name='离职时间'),
        ),
        migrations.AlterField(
            model_name='record',
            name='position',
            field=models.CharField(default='', max_length=100, verbose_name='职能'),
        ),
        migrations.AlterField(
            model_name='record',
            name='start_time',
            field=models.DateField(verbose_name='入职时间'),
        ),
        migrations.AlterField(
            model_name='record',
            name='summary',
            field=models.TextField(default='', verbose_name='概述'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='content',
            field=models.CharField(default='', max_length=200, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birthday',
            field=models.DateField(verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='blog',
            field=models.URLField(default='', verbose_name='博客'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='github',
            field=models.URLField(default='', verbose_name='GitHub'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='introduce',
            field=models.TextField(default='', verbose_name='自我介绍'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(default='', max_length=10, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='telephone',
            field=models.CharField(default='', max_length=20, verbose_name='电话'),
        ),
    ]
