# Generated by Django 2.0.2 on 2018-02-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resumes', '0006_auto_20180202_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_time',
            field=models.DateField(blank=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='record',
            name='end_time',
            field=models.DateField(blank=True, verbose_name='离职时间'),
        ),
    ]
