# Generated by Django 2.0.1 on 2018-04-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resumes', '0007_auto_20180206_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='end_time',
            field=models.DateField(blank=True, default='0000-00-00', verbose_name='离职时间'),
        ),
    ]
