# Generated by Django 2.0.1 on 2018-04-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resumes', '0008_auto_20180425_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='end_time',
            field=models.DateField(blank=True, default='', verbose_name='离职时间'),
        ),
    ]
